<?php














function cache_chk($url)
{

$storadge = file_get_contents($url."/cache-summ", true);

$global = file_get_contents("http://toun.ru/content/cache-change");

//echo $storadge." = ".md5($global);

if ($storadge == md5($global)) {
	setcookie("cache", md5($global), time()+86400);
	return true;
	
}
setcookie("cache", md5($global), time()+86400);
return false;
}


function create_cache($data)
{
$filename ="cache". $_SERVER['REQUEST_URI'];
	
	if (!is_dir($filename)) {
if (!mkdir($filename, 0777, true)) {
echo "Проблема при создани файла кеша";
}
}
	$global = file_get_contents("http://toun.ru/content/cache-change");
    file_put_contents($filename."/cache-index", $data);
	file_put_contents($filename."/cache-summ", md5($global));
}




function go2json_permission() {
  return array(
    'access go2json content' => array(
      'title' => t( 'Access Content as JSON content' ), 
      'description' => t( 'Use the go2json menu callbacks to retrieve data in JSON format' ) 
    ) 
  );
}

function rr(&$ar, $key) {
    
	foreach($ar as $k => $v) {
    if ($k == $key) $result[$key] = null;
    if (is_array($ar[$k])) rr($v, $key);
    }
	var_dump($ar);
    	
}

function go2json_menu() {
  $items ['go2json/%/%'] = array(
    'page callback' => 'go2json_get_data', 
    'page arguments' => array(
      1, 
      2 
    ), 
    'access arguments' => array(
      'access go2json content' 
    ), 
    'type' => MENU_CALLBACK 
  );
   
  return $items;
}



/**
 * Get a node by a menucallback and return as JSON
 * 
 * @param string $type The type of content (node, comment, taxonomy_term, taxonomy_vocabulary, custom_data)
 * @param int $nid     ID of content to GET, give 0 as default
 */
function go2json_get_data($type, $id) {
	
$filename ="cache". $_SERVER['REQUEST_URI'];

if(cache_chk($filename)){
	$json= file_get_contents($filename."/cache-index", true);
	echo $json;
	die;
}
	
	
  switch ($type) {
    case "node" :
      $data = _go2json_get_node( $id );
      break;
    
    case "comment" :
      $data = _go2json_get_comment( $id );
      break;
  case "comment_add" :
      $data = _go2json_add_comment( $id );
      break;
    case "menu" :
      $data = _go2json_get_menu( $id );
      break;
    
    case "term" :
      $data = _go2json_get_taxonomy_term( $id );
      break;
    
    case "taxonomy" :
      $data = _go2json_get_taxonomy_vocabulary( $id );
      break;
    
    case "custom_data" :
      $data = _go2json_get_custom_data();
      break;
    case "theme_setting" :
      $data = _go2json_get_theme_setting();
      break;
	  
	case "first" :
      $data = _go2json_first( $id );
      break;  
	 
	case "request" :
      $data = _go2json_request( $id );
      break;  
	 
	case "perfomance" :
      $data = _go2json_perfomance( $id );
      break;
	
	case "projects" :
      $data = _go2json_projects( $id );
      break;
	
	case "festival" :
      $data = _go2json_festival( $id );
      break;
	
	case "people" :
      $data = _go2json_people( $id );
	break;
		
	case "feedback" :
      $data = _go2json_feedback( $id );
	break;
	
	case "pages" :
      $data = _go2json_pages( $id );
	break;
	
	
	case "simple" :
	$data = _go2json_simple( $id );
	break;
	
    default :
      $data = _go2json_get_error_message_type( $type );
      break;
  }
  
  $data = ($data == FALSE ? _go2json_get_error_message_id( $id ) : $data);
  

	$out = (array)$data;
	(array)$out;
	
		deleteSafe($out);
		//var_dump($out);
		//die; 
		
	$replace = json_encode($out, JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE);
	//$replace = json_encode($out, JSON_HEX_TAG|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE);
	$replace = str_replace("\"ru\"","\"field_lang_ru\"",$replace);
	$replace = str_replace("\"en\"","\"field_lang_en\"",$replace);
	$replace = str_replace("\"Kh\"","\"field_lang_kh\"",$replace);
	$replace = str_replace("\"Mn\"","\"field_lang_mns\"",$replace);
	$replace = str_replace("http:\/\/toun.ru\/","/",$replace);
	$replace = str_replace("\u0022","'",$replace);
	$replace = str_replace("\u003C","<",$replace);
	$replace = str_replace("\u003E",">",$replace);
	$replace = str_replace("public:\/\/","\/content\/sites\/default\/files\/",$replace);
	//$replace =  htmlspecialchars_decode($replace);

	 
	
	
	create_cache($replace);
	echo $replace;
	
	
}


function deleteSafe( &$array )
{
    
	
	foreach( $array as $key => $val ){
        if( is_array($val) ){
            deleteSafe($array[$key]);
        }
		
		if (array_key_exists("safe_value", $array)){
            $array["safe_value"]=null;
			//var_dump($val);
		//die;
        }
    }
}


function _go2json_add_comment($id) {
  
  
  $name = $_POST["name"];
  $post = $_POST["text"];
  
 $comment = (object) array(
    'nid' => $id,
    'cid' => 0,
    'pid' => 0,
    'uid' => 1,
    'mail' => '',
	'name' => $name,
    'is_anonymous' => 0,
    'homepage' => '',
    'status' => '0',
    'subject' => 'dsk subject',
    'language' => "ru",
    'comment_body' => array(
      LANGUAGE_NONE => array(
        0 => array (
          'value' => $text,
          'format' => 'filtered_html'
        )
      )
    ),
  );

  comment_submit($comment);
  comment_save($comment);

 exit("die");
 return true;
	
	
	
}


function _in_array($s,$ar){
	foreach($ar as $k => $v) {
    if ($k == $s) 
	echo "<br>true<br>";	
	return true;
	
    }
    if (is_array($ar[$k]))  _in_array($v, $s);
	echo "<br>false<br>";	
	return false;
	
}

##ГРУППИРОВАКА ФИЛЬТРОВ В МЕНЮ
function _go2json_year_filter( $link ) {
	$input = json_decode(file_get_contents('http://toun.ru/content/ru/' . $link), true);
	//print_r($input['items']); 
	
	$count = array();
	$out = array();
	foreach ($input['items'] as $value)
	{
		$y = $value['item']['sort'];
		$link = $y;
		
		$lang =  str_replace("#","",$y);
		$years['field_link']['und'][0] =  array('value'=>$link);
		$years['field_lang_ru']['und'][0] =  array('value'=>$lang);
		$years['field_lang_en']['und'][0] =  array('value'=>$lang);
		if (!in_array($y, $count)){ array_push($out, $years);}
		$count[$y]=$y;
	}
	return $out;
}	

#
function _go2json_projects( $id ) {
	
	if ( $id == "repertuar")
	{
		$projects['static']['field_lang_en']['title'] = "Репертуар";
		$projects['static']['field_lang_ru']['title'] = "Repertuar";
		$projects['static']['field_lang_kh']['title'] = "переовод:KH";
		$projects['static']['field_lang_mns']['title'] = "Перевод:MNS";
		$projects['widget'] =_go2json_glue_page('repertuar');
		$projects['filter_menu'] = _go2json_year_filter('repertuar');
		$projects['seo']["field_lang_en"]['title'] = "Repertuar";
		$projects['seo']["field_lang_ru"]['title'] = "Репертуар";
		$projects['seo']["field_lang_ru"]['description'] = "Репертуар театра СОЛНЦЕ";
		$projects['seo']["field_lang_en"]['description'] = "repertuar thetre SUN";
	}
	
	
	if ( $id == "new")
	{
		$projects['static']['field_lang_en']['title'] = "Новые дела";
		$projects['static']['field_lang_ru']['title'] = "New projects";
		$projects['static']['field_lang_kh']['title'] = "переовод:KH";
		$projects['static']['field_lang_mns']['title'] = "Перевод:MNS";
		$projects['widget'] =_go2json_glue_page('projects');
		$projects['filter_menu'] = _go2json_get_taxonomy_vocabulary('menu_projects');
		$projects['seo']["field_lang_en"]['title'] = "NEW Projects";
		$projects['seo']["field_lang_ru"]['title'] = "Новые дела";
		$projects['seo']["field_lang_ru"]['description'] = "Премьерные постановки театра СОЛНЦЕ";
		$projects['seo']["field_lang_en"]['description'] = "premier thetre SUN";
	}
	

 
	
	$replace = json_encode($projects, JSON_HEX_QUOT);
	
	//$replace = str_replace("\u0022","!!!",$replace);
	//\u0022
	//echo $replace;
	//exit();
	$projects = json_decode($replace);
	return $projects;
}

#Вроде не используется
function _go2json_get_node($id) {
  //$node = node_load( $id );
  $node = node_load( $id );
  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
      return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  $node["field_project_people"]["und"][0]["safe_value"] = "null";

  return $node;
}


function _go2json_get_comment($id) {
  
  
  // Check permissions
  // Make hook available
  $comment_array = module_invoke_all( "go2json_get_comment", $comment );
  if (is_array( $comment_array ) && ! empty( $comment_array )) {
    $comment = $comment_array;
  }
  
  return $comment;
}


function _go2json_microtime() {
	
	$time = file_get_contents('timecache', true);
	$delta_time = microtime(true);
	
	$result =  $delta_time - $time; 
	//echo $result;
	
	//exit();
	
	$a = date('d', $time);
	$b = date('d', $delta_time);
	
	
	if ($b==$a){ 
		return true;
	}

return false;
	
}


function _go2json_glue_page($link) {
$out = array();

$ru = json_decode(file_get_contents('http://toun.ru/content/ru/' . $link), true);
$ru2 = $ru["items"];

$en = json_decode(file_get_contents('http://toun.ru/content/en/' . $link), true);
$en2 = $en["items"];

$kh = json_decode(file_get_contents('http://toun.ru/content/kh/' . $link), true);
$kh2 = $kh["items"];

$mns = json_decode(file_get_contents('http://toun.ru/content/mns/' . $link), true);
$mns2 = $mns["items"];


$i=1;
foreach ($ru2 as $value) {
	
	$out[$i]['field_lang_ru'] = $value;
	$i++;
}

$i=1;
foreach ($en2 as $value) {
	
	$out[$i]['field_lang_en'] = $value;
	$i++;
}

$i=1;
foreach ($kh2 as $value) {
	
	$out[$i]['field_lang_kh'] = $value;
	$i++;
}


$i=1;
foreach ($mns2 as $value) {
	
	$out[$i]['field_lang_mns'] = $value;
	$i++;
}
 
 	
 
 
 
 return $out;

}


function _go2json_glue($link) {
$out = array();

$ru = json_decode(file_get_contents('http://toun.ru/content/ru/' . $link), true);
$ru2 = $ru["items"];

$en = json_decode(file_get_contents('http://toun.ru/content/en/' . $link), true);
$en2 = $en["items"];

$kh = json_decode(file_get_contents('http://toun.ru/content/kh/' . $link), true);
$kh2 = $kh["items"];

$mns = json_decode(file_get_contents('http://toun.ru/content/mns/' . $link), true);
$mns2 = $mns["items"];


$i=1;
foreach ($ru2 as $value) {
	
	$out[$i]['field_lang_ru'] = $value;
	$i++;
}

$i=1;
foreach ($en2 as $value) {
	
	$out[$i]['field_lang_en'] = $value;
	$i++;
}

$i=1;
foreach ($kh2 as $value) {
	
	$out[$i]['field_lang_kh'] = $value;
	$i++;
}


$i=1;
foreach ($mns2 as $value) {
	
	$out[$i]['field_lang_mns'] = $value;
	$i++;
}
 
 return $out;
 
}


function _go2json_get_status_cache($file) {
	$cache = md5(file_get_contents('http://toun.ru/content/cache-change'));
	$request = file_get_contents($file, true);
	//setcookie("update", $cache, time()+86400);
	if ($request === $cache) {
	return true;
  
}
file_put_contents($file, $cache);
return false;
}


function _go2json_people($id) {
 //$node = node_load( $id );

 if ($id == "view"){
	
$out['widget'] = _go2json_glue("people");
	
	$out['seo']["field_lang_en"]['title'] = "Хозяева";
	$out['seo']["field_lang_ru"]['title'] = "People";
	$out['seo']["field_lang_ru"]['description'] = "сотрудники театра СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "people teathre SUN";
  
	$out['filter_menu'] = _go2json_get_taxonomy_vocabulary('people_category');
  return  $out; 
 }
 
 
 $node = node_load( $id );
 $node = (array)$node;
  // Check if the node exists
 if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }

if ($node["type"] != 'people') {
  // drupal_add_http_header('Status', '404', $append = FALSE);
//return;
 }  
 
 
  $out['page'] = $node;
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field_description_perfomance"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field_description_perfomance"]["en"][0]["value"];
  $out['filter_menu'] = _go2json_get_taxonomy_vocabulary('people_category');
   $out['page']['static']['field_lang_ru']['more_button']="Подробнее";
  $out['page']['static']['field_lang_ru']['more_button']="more";
  $out['page']['static']['field_lang_ru']['send_button']="Отправить";
  $out['page']['static']['field_lang_en']['send_button']="Send";
  $out['page']['static']['field_lang_ru']['review_title']="Оставить отзыв";
  $out['page']['static']['field_lang_en']['review_title']="Send review";
  $out['page']['static']['field_lang_ru']['placeholder_text']="Ваше сообщение";
  $out['page']['static']['field_lang_en']['placeholder_text']="You message";
  $out['page']['static']['field_lang_ru']['placeholder_name']="Ваше Имя и Фамилия";
  $out['page']['static']['field_lang_en']['placeholder_name']="You Name";
  return  $out;
 
}


function _go2json_perfomance($id) {
 //$node = node_load( $id );
$node = node_load( $id );




  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  
  
if ($node["type"] != 'perfomance') {
   drupal_add_http_header('Status', '404', $append = FALSE);
return;
 }  
 
 
 
  //var_dump($node);
//exit();  
  $out['page'] = $node;
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field_description_perfomance"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field_description_perfomance"]["en"][0]["value"];
  
  $out['page']['static']['field_lang_ru']['send_button']="Отправить";
  $out['page']['static']['field_lang_en']['send_button']="Send";
  $out['page']['static']['field_lang_ru']['review_title']="Оставить отзыв";
  $out['page']['static']['field_lang_en']['review_title']="Send review";
  $out['page']['static']['field_lang_ru']['placeholder_text']="Ваше сообщение";
  $out['page']['static']['field_lang_en']['placeholder_text']="You message";
  $out['page']['static']['field_lang_ru']['placeholder_name']="Ваше Имя и Фамилия";
  $out['page']['static']['field_lang_en']['placeholder_name']="You Name";
  
  // comment_node_load( $id, );
  $out['comments'] = comment_view_multiple($coms, $node);
  return  $out;
 
}


function _go2json_festival($id) {
 //$node = node_load( $id );
  $node = node_load( $id );
// если нужно ддобавить новый фестиваль то это делается так: меню загружается из термина таксономи по id, а у  фестиваля будет сортивка по терминам таксонмии. и у каждого свое меню





$cids = comment_get_thread($node, 'COMMENT_PUBLISHED', 100);
$coms = comment_load_multiple($cids);




  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  
  //var_dump($node);
//exit();  


if ($node["type"] != 'festival') {
   drupal_add_http_header('Status', '404', $append = FALSE);
return;
 }
 
 
  $out['page'] = $node;
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field__seo_"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field__seo_"]["en"][0]["value"];
  
  $out['page']['static']['field_lang_ru']['send_button']="Отправить";
  $out['page']['static']['field_lang_en']['send_button']="Send";
  $out['page']['static']['field_lang_ru']['review_title']="Оставить отзыв";
  $out['page']['static']['field_lang_en']['review_title']="Send review";
  $out['page']['static']['field_lang_ru']['placeholder_text']="Ваше сообщение";
  $out['page']['static']['field_lang_en']['placeholder_text']="You message";
  $out['page']['static']['field_lang_ru']['placeholder_name']="Ваше Имя и Фамилия";
  $out['page']['static']['field_lang_en']['placeholder_name']="You Name";
  
  // comment_node_load( $id, );
  $out['comments'] = comment_view_multiple($coms, $node);
  $out['filter_menu'] = _go2json_get_taxonomy_vocabulary('menu_white');
  return  $out;
 
}


function _go2json_first( $id ) {
	
 switch ($id) {
    case "frontpage" :
      $data = _frontpage();
      break;
	  
	case "global" :
      $data = _global();
      break;  
	  
	
	  
}
	
	return $data;
}


function _go2json_request( $id ) {
	
 switch ($id) {

	case "awards" :
      $data = _awards();
      break;
	  
	  case "video" :
      $data = _videogallery();
      break;
	  
	  case "library" :
      $data = _library();
      break; 
	  
	case "documents" : 
      $data = _documents();
      break; 
	  
	 case "vacancy" : 
      $data = _vacancy();
      break; 
	  
	 case "press" : 
      $data = _press();
      break; 

	  	 case "partners" : 
      $data = _partners();
      break; 
	  
	case "news" : 
      $data = _news();
      break; 
	 
	case "afisha" : 
      $data = _afisha();
      break; 
	  }
	
	return $data;
}


function _go2json_get_menu($id) {
  $menu = menu_tree_all_data( $id );
  // Check permissions
  if (user_access( 'access content' ) != TRUE) {
    return _go2json_get_error_message_permission( 'menu', $id );
  }

  // Make hook available
  $menu_array = module_invoke_all( "go2json_get_menu", $menu );
  if (is_array( $menu_array ) && ! empty( $menu_array )) {
    $menu = $menu_array;
  }
 ///print_r($menu);
  return $menu;
}
 

function _go2json_get_taxonomy_term($id) {
  $taxonomy_term = taxonomy_term_load($id);
  
  // Make hook available
  $taxonomy_term_array = module_invoke_all( "go2json_get_taxonomy_term", $taxonomy_term );
  if (is_array( $taxonomy_term_array ) && ! empty( $taxonomy_term_array )) {
    $taxonomy_term = $taxonomy_term_array;
  }
  
  return $taxonomy_term;
}

 
function onix_reportes_build_tree($flatTree){
	$tree = array();
	$last_term_stack = array();
	foreach ($flatTree as &$term) {
		while(count($last_term_stack) > 0){
			if(in_array(end($last_term_stack)->tid, $term->parents)) {
					$lastTerm = end($last_term_stack);
					$lastTerm->children[]=$term;
					array_push($last_term_stack,$term);
					break;
				} else {
					array_pop($last_term_stack);
				}
		}
		if(empty($last_term_stack)){
			$tree[] =$term;
			array_push($last_term_stack, $term);
		} 
	}
	return $tree;
} 
 
 
function _go2json_get_taxonomy_vocabulary($id) {
  $taxonomy_vocabulary = taxonomy_vocabulary_machine_name_load($id);
  //$taxonomy_vocabulary2 = taxonomy_get_tree($taxonomy_vocabulary->vid);
  $tree = taxonomy_get_tree($taxonomy_vocabulary->vid, $parent = 0, $max_depth = NULL, $load_entities = TRUE);
  // Make hook available
  
  $tree = onix_reportes_build_tree($tree);

  
  return $tree;
  
  

  
}


function _go2json_get_custom_data() {
  $custom_data = FALSE;
  
  // Make hook available
  $custom_data_array = module_invoke_all( "go2json_get_custom_data", $custom_data );
  if (is_array( $custom_data_array ) && ! empty( $custom_data_array )) {
    $custom_data = $custom_data_array;
  }
  
  return $custom_data;
}


function _go2json_get_theme_setting() {
$theme_setting['site_name'] = variable_get('site_name', "Default site name");
$theme_setting['favicon'] = theme_get_setting('favicon');

$theme_setting['phone_first'] = theme_get_setting('bootstrap_phone_first');
$theme_setting['phone_second'] = theme_get_setting('bootstrap_phone_second');
$theme_setting['field_lang_en']['logo_vertical'] = theme_get_setting('bootstrap_en_logo2');
$theme_setting['field_lang_en']['logo_vertical_invert'] = theme_get_setting('bootstrap_en_logo_invert2');
$theme_setting['field_lang_ru']['logo_vertical'] = theme_get_setting('bootstrap_ru_logo2');
$theme_setting['field_lang_ru']['logo_vertical_invert'] = theme_get_setting('bootstrap_ru_logo_invert2');
$theme_setting['field_lang_en']['logo_horisontal'] = theme_get_setting('bootstrap_en_logo1');
$theme_setting['field_lang_en']['logo_horisontal_invert'] = theme_get_setting('bootstrap_en_logo_invert1');
$theme_setting['field_lang_ru']['logo_horisontal'] = theme_get_setting('bootstrap_ru_logo1');
$theme_setting['field_lang_ru']['logo_horisontal_invert'] = theme_get_setting('bootstrap_ru_logo_invert1');




  return $theme_setting;
}


function _go2json_get_footer() {
$footer['mail'] = theme_get_setting('bootstrap_mail');
$footer['link_vk'] = theme_get_setting('bootstrap_link_vk');
$footer['link_facebook'] = theme_get_setting('bootstrap_link_facebook');
$footer['link_youtube'] = theme_get_setting('bootstrap_link_youtube');
$footer['link_instagram'] = theme_get_setting('bootstrap_link_instagram');
$footer['field_lang_ru']['adress_footer'] = theme_get_setting('bootstrap_ru_adress_footer');	
$footer['field_lang_en']['adress_footer'] = theme_get_setting('bootstrap_en_adress_footer');
return $footer;
}


function _go2json_get_head() {
$head['field_lang_ru']['adress_head'] = theme_get_setting('bootstrap_ru_adress_head');
$head['field_lang_ru']['slogan_top'] = theme_get_setting('bootstrap_ru_slogan_top');
$head['field_lang_en']['slogan_top'] = theme_get_setting('bootstrap_en_slogan_top');
$head['field_lang_en']['adress_head'] = theme_get_setting('bootstrap_en_adress_head');

$head['field_lang_ru']['eyesight'] = theme_get_setting('bootstrap_ru_eyesight');
$head['field_lang_en']['eyesight'] = theme_get_setting('bootstrap_en_eyesight');
$head['bootstrap_eyesight_link'] = theme_get_setting('bootstrap_eyesight_link');




$head['field_lang_ru']['title_map'] = theme_get_setting('bootstrap_ru_title_map');
$head['field_lang_en']['title_map'] = theme_get_setting('bootstrap_en_title_map');
$head['sun_link'] = "/video";
$head['map_link'] = "/video";
return $head;
}


function _go2json_get_lenta() {
    
$lenta['video_lenta_mp4'] = theme_get_setting('bootstrap_video_lenta_mp4');
$lenta['video_lenta_webm'] = theme_get_setting('bootstrap_video_lenta_webm');
$lenta['video_lenta_ogv'] = theme_get_setting('bootstrap_video_lenta_ogv');
$lenta['video_lenta_jpg'] = theme_get_setting('bootstrap_video_lenta_jpg');
$lenta['video_lenta_link'] = theme_get_setting('bootstrap_video_lenta_link');
$lenta['video_lenta_link'] = "/test";


  return $lenta;
}


function _go2json_get_error_message_permission($type, $id) {
  return array(
    "error" => t( "You don't have any permissions to view this content. The arguments were (@type) and (@id)", array(
      "@type" => $type, 
      "@id" => $id 
    ) ) 
  );
}


function _go2json_get_error_message_type($type) {
  drupal_add_http_header('Status', '404', $append = FALSE);
  return array(
    "error" => t( "No valid content type given to go2json callback. The argument was (@type)", array(
      "@type" => $type 
    ) ) 
  );
}


function _go2json_get_error_message_id($id) {
  drupal_add_http_header('Status', '404', $append = FALSE);
  //header("HTTP/1.x 404 Not Found");
  header("HTTP/1.0 404 Not Found");
  header($_SERVER['SERVER_PROTOCOL']." 404 Not Found");
  //exit();
  //return header("HTTP/1.0 404 Not Found");
  return array(
    "error" => t( "404", array(
      "@id" => $id 
    ) ) 
  );
}


function _go2json_get_error_message_content_inexistent($type, $id) {
  return array(
    "error" => t( "The content doesn't exist. The arguments were (@type) and (@id)", array(
        "@type" => $type,
        "@id" => $id
      )
    )
  );
}


function _global(){
	
	$out['settings'] = _go2json_get_theme_setting();
	$out['menu'] = _go2json_get_taxonomy_vocabulary('menu');
	$out['footer'] = _go2json_get_footer();
	
	return $out;
	
}
	
	
function _press(){
	
	$out['widget'] = _go2json_glue("press");
	$out['static']["field_lang_en"]["header"] = "Press";
	$out['static']["field_lang_ru"]["header"] = "Пресса"; 
	$out['static']["field_lang_kh"]["header"] =  "Пресс(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "Персс(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Вакансии";
	$out['seo']["field_lang_ru"]['title'] = "Вакансии";
	$out['seo']["field_lang_ru"]['description'] = "Вакансии театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Вакансии teathre SUN";

	return $out;
}	

function _awards(){
	$out['widget'] = _go2json_glue("awards");
	$out['static']["field_lang_en"]["header"] = "Awards";
	$out['static']["field_lang_ru"]["header"] = "Награды"; 
	$out['static']["field_lang_kh"]["header"] =  "Награды(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "Награды(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Награды";
	$out['seo']["field_lang_ru"]['title'] = "Awards";
	$out['seo']["field_lang_ru"]['description'] = "награды театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "awards teathre SUN";
  
	$out['filter_menu'] = _go2json_year_filter('awards');

	return $out;
}
	
function _library(){
	$out['widget'] = _go2json_glue("library");
	$out['static']["field_lang_en"]["header"] = "Library";
	$out['static']["field_lang_ru"]["header"] = "Библиотека"; 
	$out['static']["field_lang_kh"]["header"] =  "библиотекаы(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "выаваы(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Библиотека";
	$out['seo']["field_lang_ru"]['title'] = "Library";
	$out['seo']["field_lang_ru"]['description'] = "Библиотека театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Library SUN";
	$out['filter_menu'] = _go2json_get_taxonomy_vocabulary('library_cate');
	
	return $out;
}	
 
function _videogallery(){
	
	$out['widget'] = _go2json_glue("video");
	$out['static']["field_lang_en"]["header"] = "Video gallery";
	$out['static']["field_lang_ru"]["header"] = "Видео галлерея"; 
	$out['static']["field_lang_kh"]["header"] =  "Награды(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "Награды(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Видео галлерея";
	$out['seo']["field_lang_ru"]['title'] = "Video gallery";
	$out['seo']["field_lang_ru"]['description'] = "Видео галлерея театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Video gallery SUN";
  
	$out['filter_menu'] = _go2json_get_taxonomy_vocabulary('video_catalog');
	
	return $out;
}	
	
	
	function _vacancy(){
	
	$out['widget'] = _go2json_glue("vacancy");
	$out['static']["field_lang_en"]["header"] = "Вакансии";
	$out['static']["field_lang_ru"]["header"] = "Vacancy"; 
	$out['static']["field_lang_kh"]["header"] =  "Вакансии(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "вакансии(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Вакансии";
	$out['seo']["field_lang_ru"]['title'] = "Вакансии";
	$out['seo']["field_lang_ru"]['description'] = "Вакансии театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Вакансии teathre SUN";
 
	return $out;
}

	function _partners(){
	
	$out['widget'] = _go2json_glue("partners");
	$out['static']["field_lang_en"]["header"] = "Партнеты";
	$out['static']["field_lang_ru"]["header"] = "partners"; 
	$out['static']["field_lang_kh"]["header"] =  "srhи(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "вsfgsсии(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Партнеты";
	$out['seo']["field_lang_ru"]['title'] = "Партнеты";
	$out['seo']["field_lang_ru"]['description'] = "partners театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "partners teathre SUN";

	return $out;
}
	
	
function _frontpage(){ 

/* if (_go2json_microtime()===true && _go2json_get_status_cache('frontchek')===true)
	


{
	$request = json_decode(file_get_contents('frontcache', true));
	
} else { */


	$lang = array();
	$month = mb_strtolower(date("M"));
	$next_month = mb_strtolower(date("M", strtotime("+1 month")));
	
	$xru = "bootstrap_langru" . $month;
	$xen = "bootstrap_langen" . $month;
	$xkh = "bootstrap_langkh" . $month;
	$xmns = "bootstrap_langmns" . $month;

	$lang['first_month']['ru']= theme_get_setting($xru);
	$lang['first_month']['en']= theme_get_setting($xen);
	$lang['first_month']['kh']= theme_get_setting($xkh);
	$lang['first_month']['mns']= theme_get_setting($xmns);
	
	$xru = "bootstrap_langru" . $next_month;
	$xen = "bootstrap_langen" . $next_month;
	$xkh = "bootstrap_langkh" . $next_month;
	$xmns = "bootstrap_langmns" . $next_month;
	
	$lang['second_month']['ru']=theme_get_setting($xru);
	$lang['second_month']['en']=theme_get_setting($xen);
	$lang['second_month']['kh']=theme_get_setting($xkh);
	$lang['second_month']['mns']=theme_get_setting($xmns);
	
	
	$request = array();
	$request['header'] = _go2json_get_head();
	$request['lenta'] = _go2json_get_lenta();
	
	$request['seo']["field_lang_en"]['title'] = "Theatre SUN";
	$request['seo']["field_lang_ru"]['title'] = "Театр солнце";
	$request['seo']["field_lang_ru"]['description'] = "";
	$request['seo']["field_lang_en"]['description'] = "";	
 
	
	$request['2-day']['widget'] = _go2json_glue("widget-afisha-2-day");
	$request['2-day']['static']['field_lang_ru']['title'] = theme_get_setting('bootstrap_langru2day');
	$request['2-day']['static']['field_lang_en']['title'] = theme_get_setting('bootstrap_langen2day');
	$request['2-day']['static']['field_lang_kh']['title'] = theme_get_setting('bootstrap_langkh2day');
	$request['2-day']['static']['field_lang_mns']['title'] = theme_get_setting('bootstrap_langmns2day');
	
	$request['afisha']['widget']['first_month']  = _go2json_glue("widget-afisha-1");
	
		
	$request['afisha']['static']['first_month']['field_lang_ru']['title'] = $lang['first_month']['ru'];
	$request['afisha']['static']['first_month']['field_lang_en']['title'] = $lang['first_month']['en'];
	$request['afisha']['static']['first_month']['field_lang_kh']['title'] = $lang['first_month']['kh'];
	$request['afisha']['static']['first_month']['field_lang_mns']['title'] = $lang['first_month']['mns'];

	
	$request['afisha']['widget']['second_month']  = _go2json_glue("widget-afisha-2");
		
	$request['afisha']['static']['second_month']['field_lang_ru']['title'] = $lang['second_month']['ru'];
	$request['afisha']['static']['second_month']['field_lang_en']['title'] = $lang['second_month']['en'];
	$request['afisha']['static']['second_month']['field_lang_kh']['title'] = $lang['second_month']['kh'];
	$request['afisha']['static']['second_month']['field_lang_mns']['title'] = $lang['second_month']['mns'];
	
	$request['news']['widget']  = _go2json_glue("widget-list-news");
	$request['news']['static']['field_lang_ru']['title'] = "Новости";
	$request['news']['static']['field_lang_en']['title'] = "News";
	$request['news']['static']['field_lang_kh']['title'] = "навста";
	$request['news']['static']['field_lang_mns']['title'] = "навсты";
	$request['news']['static']['field_lang_ru']['more'] = "Подробнее";
	$request['news']['static']['field_lang_en']['more'] = "More";
	$request['news']['static']['field_lang_ru']['other'] = "Другие новости театра";
	$request['news']['static']['field_lang_en']['other'] = "Other news teatre";
	$request['news']['static']['field_lang_ru']['other'] = "Другие новости театра";
	$request['news']['static']['link'] = "/news";
	
	
	
	
	//$reccache = json_encode($request);
	///file_put_contents('frontcache', $reccache);
	///$time = microtime(true);
	///file_put_contents('timecache', $time);
	//_go2json_get_status_cache('frontchek');

return $request;
} 

function _documents(){
	
	$out['widget'] = _go2json_glue("documents");
	$out['static']["field_lang_en"]["header"] = "Documents";
	$out['static']["field_lang_ru"]["header"] = "Документы"; 
	$out['static']["field_lang_kh"]["header"] =  "Документы(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "Документы(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Документы";
	$out['seo']["field_lang_ru"]['title'] = "Документы";
	$out['seo']["field_lang_ru"]['description'] = "Документы театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Документы gallery SUN";
  
	$out['filter_menu'] = _go2json_year_filter('documents');
	
	return $out;
}	

function _news(){
	
	$out['widget'] = _go2json_glue("news");
	$out['static']["field_lang_en"]["header"] = "NEWS";
	$out['static']["field_lang_ru"]["header"] = "Новости"; 
	$out['static']["field_lang_kh"]["header"] =  "ydjjf(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "новости(хнт)";
	$out['seo']["field_lang_en"]['title'] = "NEWS";
	$out['seo']["field_lang_ru"]['title'] = "Новости";
	
	$out['static']["field_lang_en"]['back'] = "Back";
	$out['static']["field_lang_ru"]['back'] = "Предыдущая страница";
	
	$out['static']["field_lang_en"]['next'] = "next";
	$out['static']["field_lang_ru"]['next'] = "Следущая страница";
	
	$out['static']["field_lang_en"]['more'] = "more";
	$out['static']["field_lang_ru"]['more'] = "подробнее";
	
	$out['static']["field_lang_en"]['from'] = "from";
	$out['static']["field_lang_ru"]['from'] = "из";
	$out['seo']["field_lang_ru"]['description'] = "Новости театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "news gallery SUN";
  
	return $out;
}	
function _afisha(){
	
	$lang = array();
	$month = mb_strtolower(date("M"));
	$next_month = mb_strtolower(date("M", strtotime("+1 month")));
	
	$xru = "bootstrap_langru" . $month;
	$xen = "bootstrap_langen" . $month;
	$xkh = "bootstrap_langkh" . $month;
	$xmns = "bootstrap_langmns" . $month;

	$lang['first_month']['ru']= theme_get_setting($xru);
	$lang['first_month']['en']= theme_get_setting($xen);
	$lang['first_month']['kh']= theme_get_setting($xkh);
	$lang['first_month']['mns']= theme_get_setting($xmns);
	
	$xru = "bootstrap_langru" . $next_month;
	$xen = "bootstrap_langen" . $next_month;
	$xkh = "bootstrap_langkh" . $next_month;
	$xmns = "bootstrap_langmns" . $next_month;
	
	$lang['second_month']['ru']=theme_get_setting($xru);
	$lang['second_month']['en']=theme_get_setting($xen);
	$lang['second_month']['kh']=theme_get_setting($xkh);
	$lang['second_month']['mns']=theme_get_setting($xmns);
	
	
$out['page']['widget']['first_month']  = _go2json_glue("widget-afisha-1");
	
		
	$out['page']['static']['first_month']['field_lang_ru']['title'] = $lang['first_month']['ru'];
	$out['page']['static']['first_month']['field_lang_en']['title'] = $lang['first_month']['en'];
	$out['page']['static']['first_month']['field_lang_kh']['title'] = $lang['first_month']['kh'];
	$out['page']['static']['first_month']['field_lang_mns']['title'] = $lang['first_month']['mns'];
	
	$out['page']['static']['field_lang_ru']['all'] = "Посмотреть афишу полностью";
	$out['page']['static']['field_lang_en']['all'] = "view all";
	$out['page']['static']['link'] = "/afisha";
	
	$out['page']['widget']['second_month']  = _go2json_glue("widget-afisha-2");
		
	$out['page']['static']['second_month']['field_lang_ru']['title'] = $lang['second_month']['ru'];
	$out['page']['static']['second_month']['field_lang_en']['title'] = $lang['second_month']['en'];
	$out['page']['static']['second_month']['field_lang_kh']['title'] = $lang['second_month']['kh'];
	$out['page']['static']['second_month']['field_lang_mns']['title'] = $lang['second_month']['mns'];
	
	$out['static']["field_lang_en"]["header"] = "AFISHA";
	$out['static']["field_lang_ru"]["header"] = "Афиша"; 
	
	
	

	
	

	
	$out['static']["field_lang_en"]["event"] = "Event";
	$out['static']["field_lang_ru"]["event"] = "Мероприятие"; 
	
	$out['static']["field_lang_en"]["time"] = "Time";
	$out['static']["field_lang_ru"]["time"] = "Время"; 
	
	$out['static']["field_lang_en"]["header"] = "AFISHA";
	$out['static']["field_lang_ru"]["header"] = "Место"; 
	
		
	$out['static']["field_lang_en"]["Price"] = "Price";
	$out['static']["field_lang_ru"]["Price"] = "Цена билета"; 
	
	$out['static']["field_lang_kh"]["header"] =  "ФАШЫОА(мнс)";
	$out['static']["field_lang_mns"]["header"] =  "вафыва(хнт)";
	$out['seo']["field_lang_en"]['title'] = "Afisha";
	$out['seo']["field_lang_ru"]['title'] = "Афиша";
	$out['seo']["field_lang_ru"]['description'] = "Афиша театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Afisha gallery SUN";
  
	return $out;
}	


function _go2json_feedback($id){
	
	 //$node = node_load( $id );
  $node = node_load( $id );
// если нужно ддобавить новый фестиваль то это делается так: меню загружается из термина таксономи по id, а у  фестиваля будет сортивка по терминам таксонмии. и у каждого свое меню





$cids = comment_get_thread($node, 'COMMENT_PUBLISHED', 100);
$coms = comment_load_multiple($cids);




  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  
  //var_dump($node);
//exit();  


if ($node["type"] != 'feedback') {
   drupal_add_http_header('Status', '404', $append = FALSE);
return;
 }
 
  if (date("Y") === date('Y', $node['created'])){
	  $comment_form = true;
  } else { $comment_form = false; }
  
  
  $out['page'] = $node;
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field__seo_"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field__seo_"]["en"][0]["value"];
  $out['comments'] = comment_view_multiple($coms, $node);
  
  $out['page']['static']['field_lang_ru']['send_button']="Отправить";
  $out['page']['static']['field_lang_en']['send_button']="Send";
  $out['page']['static']['field_lang_ru']['review_title']="Оставить отзыв";
  $out['page']['static']['field_lang_en']['review_title']="Send review";
  $out['page']['static']['field_lang_ru']['placeholder_text']="Ваше сообщение";
  $out['page']['static']['field_lang_en']['placeholder_text']="You message";
  $out['page']['static']['field_lang_ru']['placeholder_name']="Ваше Имя и Фамилия";
  $out['page']['static']['field_lang_en']['placeholder_name']="You Name";
  
   $out['page']['static']['coment_form'] = $comment_form;
	$out['seo']["field_lang_en"]['title'] = "Книга отзывов";
	$out['seo']["field_lang_ru"]['title'] = "Book reviews";
	$out['seo']["field_lang_ru"]['description'] = "Документы театр СОЛНЦЕ";
	$out['seo']["field_lang_en"]['description'] = "Документы gallery SUN";
  
	$out['filter_menu'] = _go2json_get_taxonomy_vocabulary('feedback');
	
	return $out;
}	

function _go2json_pages($id){
	
	 //$node = node_load( $id );
  $node = node_load( $id );
// если нужно ддобавить новый фестиваль то это делается так: меню загружается из термина таксономи по id, а у  фестиваля будет сортивка по терминам таксонмии. и у каждого свое меню





$cids = comment_get_thread($node, 'COMMENT_PUBLISHED', 100);
$coms = comment_load_multiple($cids);




  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  
  //var_dump($node);
//exit();  


if ($node["type"] != 'pages') {
   drupal_add_http_header('Status', '404', $append = FALSE);
return;
 }
 
  if (date("Y") === date('Y', $node['created'])){
	  $comment_form = true;
  } else { $comment_form = false; }
  
   
  $out['page'] = $node; 
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field__seo_"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field__seo_"]["en"][0]["value"];
  $out['comments'] = comment_view_multiple($coms, $node);
  
  
  $out['page']['static']['field_lang_ru']['more_button']="Подробнее";
  $out['page']['static']['field_lang_ru']['more_button']="more";
  $out['page']['static']['field_lang_ru']['send_button']="Отправить";
  $out['page']['static']['field_lang_en']['send_button']="Send";
  $out['page']['static']['field_lang_ru']['review_title']="Оставить отзыв";
  $out['page']['static']['field_lang_en']['review_title']="Send review";
  $out['page']['static']['field_lang_ru']['placeholder_text']="Ваше сообщение";
  $out['page']['static']['field_lang_en']['placeholder_text']="You message";
  $out['page']['static']['field_lang_ru']['placeholder_name']="Ваше Имя и Фамилия";
  $out['page']['static']['field_lang_en']['placeholder_name']="You Name";
  
   $out['page']['static']['coment_form'] = $comment_form;
	
	
	return $out;
}	


function _go2json_simple($id){
	
	 //$node = node_load( $id );
  $node = node_load( $id );
// если нужно ддобавить новый фестиваль то это делается так: меню загружается из термина таксономи по id, а у  фестиваля будет сортивка по терминам таксонмии. и у каждого свое меню





$cids = comment_get_thread($node, 'COMMENT_PUBLISHED', 100);
$coms = comment_load_multiple($cids);




  $node = (array)$node;
  // Check if the node exists
  if ($node == FALSE) {
    drupal_add_http_header('Status', '404', $append = FALSE);
    //return _go2json_get_error_message_content_inexistent('node', $id);
  }
  else {
    // Check permissions
    if (node_access( 'view', $node ) != TRUE) {
     // return _go2json_get_error_message_permission( 'node', $id );
    }
  }
  
  // Make hook available
  $node_array = module_invoke_all( "go2json_get_node", $node );
  if (is_array( $node_array ) && ! empty( $node_array )) {
    $node = $node_array;
  }
  
  //var_dump($node);
//exit();  
 

if ($node["type"] != 'simple') {
   drupal_add_http_header('Status', '404', $append = FALSE);
return;
 }
 
  if (date("Y") === date('Y', $node['created'])){
	  $comment_form = true;
  } else { $comment_form = false; }
  
   
  $out['page'] = $node; 
  $out['seo']["field_lang_en"]['title'] = $node["field_title_header"]["en"][0]["value"];
  $out['seo']["field_lang_ru"]['title'] = $node["field_title_header"]["ru"][0]["value"];
  $out['seo']["field_lang_ru"]['description'] = $node["field__seo_"]["ru"][0]["value"];
  $out['seo']["field_lang_en"]['description'] = $node["field__seo_"]["en"][0]["value"];
  
  $out['page']['static']['coment_form'] = $comment_form;
	
	
	return $out;
}	