<?php

/**
 * Implements hook_filter_info().
 */
function filter_abusive_filter_info() {

  $filters['filter_abusive'] = array(
    'title' => t('JSON replace \"'),
    'description' => t('Replace all russian abusive words in the text by a given one'),
    'process callback' => '_filter_abusive_filter_process',
    'settings callback' => '_filter_abusive_filter_settings',
    'default settings' => array(
      'replace_by_word' => '\'',
    ),
  );

  return $filters;
}

/**
 * Return filter settings form.
 **/
function _filter_abusive_filter_settings($form, &$form_state, $filter, $format, $defaults) {
  $filter->settings += $defaults;

  $settings['replace_by_word'] = array(
    '#type' => 'textfield',
    '#title' => t('All words above will be replaced with this string'),
    '#default_value' => $filter->settings['replace_by_word'],
  );

  return $settings;
}

/**
 * Replace abusive words from text and return processed data.
 */
function _filter_abusive_filter_process($text, $filter) {

  // Do not process text if for non-russian language.
  global $language;
  if ($language->language != 'ru') {
    return $text;
  }

  $path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'filter_abusive') . '/classes/';
  require_once $path . 'Censure.php';
  require_once $path . 'ReflectionTypehint.php';
  require_once $path . 'UTF8.php';
  $cens = $filter->settings['replace_by_word'];
  $text =  Text_Censure::parse($text, '3', '', false, $cens, 'UTF-8');
  return $text;
}
